import { useState } from 'react'
import { Activity, ArrowUpRight, BarChart3, Bell, Building2, Check, ChevronDown, CircleHelp, CreditCard, FileClock, LayoutDashboard, Menu, Plus, Search, Settings2, ShieldCheck, Users, X } from 'lucide-react'

type NavItem = { label: string; icon: typeof LayoutDashboard }
const navigation: NavItem[] = [
  { label: 'Overview', icon: LayoutDashboard },
  { label: 'People', icon: Users },
  { label: 'Roles & access', icon: ShieldCheck },
  { label: 'Audit log', icon: FileClock },
  { label: 'Billing', icon: CreditCard },
]
const activity = [
  { initials: 'LM', name: 'Lena Morgan', action: 'invited a new member', time: '12 min ago', color: 'bg-[#f3c5b6]' },
  { initials: 'JK', name: 'Jonas Klein', action: 'updated the Analyst role', time: '48 min ago', color: 'bg-[#c7d8cb]' },
  { initials: 'SC', name: 'System', action: 'completed tenant backup', time: '2 hrs ago', color: 'bg-[#d7d0c5]' },
]

function App() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [active, setActive] = useState('Overview')
  return (
    <div className="min-h-screen bg-[#f5f3ef] text-[#1f2421]">
      <aside className={`fixed inset-y-0 left-0 z-30 flex w-[260px] flex-col border-r border-[#dedbd4] bg-[#fbfaf8] px-5 py-6 transition-transform lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="flex items-center justify-between px-2"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#e45d42] text-white shadow-sm"><Building2 size={18} /></div><div><div className="font-semibold tracking-[-.02em]">northstar</div><div className="text-[10px] font-semibold uppercase tracking-[.18em] text-[#8b908b]">control plane</div></div></div><button className="text-[#8b908b] lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X size={19} /></button></div>
        <div className="mt-10 px-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#a0a29d]">Workspace</div>
        <nav className="mt-3 space-y-1">{navigation.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setMobileOpen(false) }} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium transition ${active === label ? 'bg-[#f2e5df] text-[#b84531]' : 'text-[#656c67] hover:bg-[#f0ede8]'}`}><Icon size={17} strokeWidth={1.8} /><span>{label}</span>{label === 'Billing' && <span className="ml-auto rounded bg-[#e9e5de] px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-wider text-[#8d928c]">Soon</span>}</button>)}</nav>
        <div className="mt-10 px-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#a0a29d]">Manage</div>
        <nav className="mt-3 space-y-1"><button className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium text-[#656c67] hover:bg-[#f0ede8]"><Settings2 size={17} strokeWidth={1.8} /><span>Tenant settings</span></button></nav>
        <div className="mt-auto rounded-xl border border-[#e2ded7] bg-[#f5f1ec] p-3"><div className="flex items-center gap-2"><CircleHelp size={15} className="text-[#e45d42]" /><span className="text-xs font-semibold">Need a hand?</span></div><p className="mt-2 text-xs leading-5 text-[#777e77]">Read the setup guide or talk to our team.</p><button className="mt-3 text-xs font-bold text-[#b84531]">Open documentation <ArrowUpRight size={13} className="ml-1 inline" /></button></div>
      </aside>
      {mobileOpen && <button className="fixed inset-0 z-20 bg-[#1f2421]/20 lg:hidden" aria-label="Close navigation overlay" onClick={() => setMobileOpen(false)} />}
      <main className="lg:pl-[260px]"><header className="flex h-[76px] items-center justify-between border-b border-[#dedbd4] bg-[#fbfaf8] px-5 sm:px-9"><button className="text-[#5c655f] lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={21} /></button><div className="relative hidden w-72 sm:block"><Search size={16} className="absolute left-3 top-2.5 text-[#a2a59f]" /><input className="h-9 w-full rounded-lg border border-[#e4e1db] bg-[#f7f5f2] pl-9 pr-3 text-xs outline-none placeholder:text-[#a2a59f] focus:border-[#e45d42]" placeholder="Search workspace" /></div><div className="ml-auto flex items-center gap-4"><button className="relative text-[#777e77]" aria-label="Notifications"><Bell size={18} /><span className="absolute -right-0.5 -top-0.5 h-1.5 w-1.5 rounded-full bg-[#e45d42]" /></button><div className="h-6 w-px bg-[#e2ded7]" /><button className="flex items-center gap-2"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#d7d0c5] text-xs font-bold text-[#49514a]">LM</div><span className="hidden text-sm font-medium sm:block">Lena Morgan</span><ChevronDown size={14} className="text-[#929790]" /></button></div></header>
        <div className="mx-auto max-w-[1180px] px-5 py-8 sm:px-9 lg:py-11"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-xs font-semibold text-[#8a918b]"><span>Workspace</span><span>/</span><span className="text-[#b84531]">Overview</span></div><h1 className="mt-3 text-[31px] font-semibold tracking-[-.045em] text-[#202622]">Good morning, Lena <span className="text-[#e45d42]">●</span></h1><p className="mt-2 text-sm text-[#747b75]">Here’s what’s happening across your organization today.</p></div><button className="inline-flex w-fit items-center gap-2 rounded-lg bg-[#e45d42] px-4 py-2.5 text-sm font-semibold text-white shadow-[0_4px_12px_rgba(228,93,66,.2)] transition hover:bg-[#c94d36]"><Plus size={16} /> Invite member</button></div>
          <div className="mt-8 flex items-center justify-between rounded-xl border border-[#dedbd4] bg-[#fbfaf8] px-4 py-3 shadow-[0_1px_2px_rgba(30,32,28,.03)]"><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#f2e5df] text-[#b84531]"><Building2 size={16} /></div><div><div className="text-[11px] font-semibold uppercase tracking-[.13em] text-[#9a9e98]">Current tenant</div><div className="mt-0.5 text-sm font-semibold">Acme Corporation</div></div></div><button className="flex items-center gap-2 rounded-md border border-[#dedbd4] px-3 py-1.5 text-xs font-semibold text-[#606760]">acme-corp <ChevronDown size={14} /></button></div>
          <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: 'Active members', value: '24', trend: '+12%', icon: Users }, { label: 'Roles configured', value: '6', trend: '+2', icon: ShieldCheck }, { label: 'Events this month', value: '1,284', trend: '+18.4%', icon: Activity }, { label: 'Security score', value: '92', trend: 'Excellent', icon: BarChart3 }].map(({ label, value, trend, icon: Icon }) => <div key={label} className="rounded-xl border border-[#dedbd4] bg-[#fbfaf8] p-5 shadow-[0_1px_2px_rgba(30,32,28,.03)]"><div className="flex items-start justify-between"><span className="text-xs font-semibold text-[#828981]">{label}</span><Icon size={17} className="text-[#b2b5ae]" strokeWidth={1.7} /></div><div className="mt-4 flex items-end justify-between"><span className="text-[27px] font-semibold tracking-[-.04em]">{value}</span><span className="mb-1 text-[11px] font-bold text-[#5f876a]">{trend}</span></div></div>)}</section>
          <section className="mt-7 grid gap-5 xl:grid-cols-[1.35fr_1fr]"><div className="rounded-xl border border-[#dedbd4] bg-[#fbfaf8] p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="font-semibold tracking-[-.02em]">Workspace setup</h2><p className="mt-1 text-xs text-[#858b85]">A few steps to get your tenant ready.</p></div><span className="text-xs font-semibold text-[#b84531]">75% complete</span></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-[#ebe7e1]"><div className="h-full w-3/4 rounded-full bg-[#e45d42]" /></div><div className="mt-5 space-y-3">{['Create your organization', 'Invite your team', 'Configure roles and access', 'Connect your identity provider'].map((step, index) => <div key={step} className="flex items-center gap-3 text-sm"><div className={`flex h-5 w-5 items-center justify-center rounded-full ${index < 3 ? 'bg-[#5f876a] text-white' : 'border border-[#c9c8c2] text-transparent'}`}>{index < 3 ? <Check size={12} strokeWidth={3} /> : <span />}</div><span className={index < 3 ? 'text-[#8b918a] line-through' : 'font-medium'}>{step}</span>{index === 3 && <ArrowUpRight size={14} className="ml-auto text-[#b84531]" />}</div>)}</div></div><div className="rounded-xl border border-[#dedbd4] bg-[#fbfaf8] p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold tracking-[-.02em]">Recent activity</h2><p className="mt-1 text-xs text-[#858b85]">Latest changes in your workspace.</p></div><button className="text-xs font-bold text-[#b84531]">View all</button></div><div className="mt-4 divide-y divide-[#ebe7e1]">{activity.map((item) => <div className="flex items-center gap-3 py-3" key={item.name}><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-[10px] font-bold text-[#49514a] ${item.color}`}>{item.initials}</div><div className="min-w-0 flex-1"><p className="truncate text-xs"><span className="font-semibold">{item.name}</span> <span className="text-[#7e857f]">{item.action}</span></p><p className="mt-1 text-[10px] text-[#a1a59f]">{item.time}</p></div></div>)}</div></div></section>
        </div>
      </main>
    </div>
  )
}
export default App
